### ISSUE TITLE
How it use?

### ISSUE THREAD

**Issue by involve-it** [copleykj/socialize-user-presence#1]
How to use it in the application?
I can not update the status of the user.

**Comment by copleykj** [comment]
Basically there are three events on which you can register callbacks that run on the server to modify the status of a user, online, offline, and idle. Of the three states only the online and offline are automatic and for now the idle state is left up to you to implement if you want this functionality. The package is set up so that you can choose where to store the status. Some people still choose to store this in the user document. I prefer to create a profiles collection and have a record for each user and store this kind of information there. Below are examples taken from the README of the hooks you can register with.

``` javascript
//When the users status is online
UserPresence.onUserOnline(function(userId){
    //update the profile for the user and set it's status to online
    Meteor.profiles.update({userId:userId}, {$set:{status:"online"}})
});

//when the users status is set to idle
UserPresence.onUserIdle(function(userId){
    //update the profile for the user and set it's status to idle
    Meteor.profiles.update({userId:userId}, {$set:{status:"idle"}})
});

//when the users status is offline
UserPresence.onUserOffline(function(userId){
    //update the profile for the user and unset it's status
    Meteor.profiles.update({userId:userId}, {$unset:{status:true}})
});
```

I think this should help get you started.. Let me know if you need further help.
