### ISSUE TITLE
HCP does not reflect server-side modified code changes

### ISSUE THREAD

**Issue by diavrank** [copleykj/socialize-user-presence#19]
When the package is imported to meteor project, the "Hot Code Push" of Meteor (from server side code) seems not to be working because the changes are not reflected. In the console only shows **Meteor server restarted** but when I invoke again a meteor method it executes the old code. To see the changes I have to disconnect and connect the ddp client or reload the browser.

I verified this behavior in different apps and even, I create a basic meteor project and I only added 2 packages: **socialize:user-presence** and **mdg:validated-method**. and the issue is still present.

You can reproduce this issue following the next steps:

1. meteor create app-with-user-presence
2. cd app-with-user-presence
3. meteor add socialize:user-presence mdg:validated-method
4. replace the content of server/main.js with the following code:
````javascript
import { ValidatedMethod } from 'meteor/mdg:validated-method';

new ValidatedMethod({
	name: 'testMethod',
	validate: null,
	run() {
		console.log('entry 4');//Change the number to test
		return { hello: 'world 4' };//Change the number to test
	}
});
````
5. run meteor app: `meteor`
6. invoke the meteor method (with meteor shell, ddp-tools or Meteorman)
7. modify the meteor method and wait for "meteor server restarted" (to provoke this, maybe you should change by some moments to another app, e.g. browser, meteorman, etc)
8. **invoke again the meteor method and verify the modified code is not reflected.**
9. After that, you can remove socialize:user-presence and test again.
10. verify that the modified code is now reflected without socialize:user-presence package.

You can use this mini project to verify it:

[app-with-user-presence.zip](https://github.com/copleykj/socialize-user-presence/files/5557295/app-with-user-presence.zip)

You can use [Meteorman](https://github.com/antwaremx/meteorman) to test meteor methods.

**Comment by copleykj** [comment]
Ok, so I've narrowed this down to an issue with catching interrupt signals in `socialize:server-presence` which this package depends on. Catching them is an integral part of how the package works so removing them isn't an option. In actuality though they are not necessary when in development because there will only ever be a single server running and if it dies and restarts, then a full cleanup process will be triggered and everything should proceed normally. What I think can be done is to only catch these signals in production so that way we aren't potentially catching signals for the build tool's process, which I think may be causing this behavior.

**Comment by diavrank** [comment]
Hi @copleykj , I have just updated `socialize:server-presence` to **v1.0.3** and the issue has gone. Thank you so much for the fix.
